### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by karbassi** [todotxt/todo.txt-cli#211]
The README is lacking a few things...

- [x] Convert to Markdown.
- [x] Add Logo.
- [x] Add image/gif of it running in terminal.
- [x] Update travis-ci badge.
- [x] Add installation instructions for OS X/MacOS, Windows, and Linux
- [x] Add Code of Conduct link. (via #216)
- [x] Add Contributing link. (via #210)
- [x] Add Changelog link. (via #209)
